jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /cine
      session:
         timeout: 21600s
springdoc:
   swagger-ui:
      path: /swagger-ui.html
spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mariadb://localhost:3306/cine
      username: root
      password: jose.diaz
      hikari:
         poolName: pool
