select id_funcion, id_pelicula, nombre_teatro_funcion, sala_funcion, dia_funcion, hora_funcion, valor_funcion, categoria_audio_funcion,
categoria_subtitulos_funcion, categoria_dimension_visual_funcion
from funcion